/**
 * Pins the INTIP app target (Release config only) to manual code signing
 * instead of Xcode's automatic signing.
 *
 * Why this exists: the CI Archive step used to pass `-allowProvisioningUpdates`
 * so Xcode would resolve/create the signing identity itself via the App Store
 * Connect API. That only works when the target's own signing style is
 * Automatic — which it was, since nothing in the generated `ios/` project
 * (gitignored, regenerated by `expo prebuild` every run) ever pinned it to
 * Manual. Automatic signing on a throwaway CI keychain that gets deleted at
 * the end of every job means the private key for any certificate Xcode
 * *creates* during that run is destroyed right after — so next run it tries
 * to create another one. Apple's account-wide certificate quota (low for
 * "iOS Development") eventually fills up with orphaned certs, and Archive
 * fails with "Choose a certificate to revoke" (CI#53).
 *
 * The already-imported distribution `.p12` + provisioning profile (CI
 * secrets `IOS_DISTRIBUTION_CERTIFICATE_P12_BASE64` /
 * `IOS_PROVISIONING_PROFILE_BASE64`) were never actually being used because
 * of this — Automatic signing ignores them. This plugin makes the target use
 * them instead, so no certificate ever gets created at build time.
 *
 * `ios/` is gitignored and rebuilt by `expo prebuild` every time, so
 * hand-editing the Xcode project doesn't stick — same reasoning as
 * `withAndroidReleaseSigning.js` for the Android side.
 *
 * Activation: only when `IOS_PROVISIONING_PROFILE_NAME` is set in the
 * environment at prebuild time (CI decodes the profile and extracts its
 * `Name` before running `expo prebuild --platform ios` — see
 * `.github/workflows/ci.yml`, "Import signing credentials"). Without it this
 * plugin is a no-op, so local `expo prebuild` / `expo run:ios` is unaffected
 * and keeps using Xcode's normal Automatic signing.
 */
const { withXcodeProject } = require("expo/config-plugins");

const TARGET_NAME = "INTIP";
const BUILD_CONFIG = "Release";

module.exports = function withIOSManualSigning(config) {
  return withXcodeProject(config, (cfg) => {
    const profileName = process.env.IOS_PROVISIONING_PROFILE_NAME;
    if (!profileName) {
      return cfg;
    }
    const team = process.env.IOS_DEVELOPMENT_TEAM || "AANGG4Q668";

    const proj = cfg.modResults;
    proj.updateBuildProperty("CODE_SIGN_STYLE", "Manual", BUILD_CONFIG, TARGET_NAME);
    proj.updateBuildProperty(
      "PROVISIONING_PROFILE_SPECIFIER",
      `"${profileName}"`,
      BUILD_CONFIG,
      TARGET_NAME,
    );
    // "iPhone Distribution" is the generic identity string Xcode has always
    // matched against — it resolves to whichever cert is actually installed,
    // old-style "iPhone Distribution: ..." or the current "Apple
    // Distribution: ...", so this doesn't need to know which one the
    // imported .p12 actually contains.
    proj.updateBuildProperty(
      "CODE_SIGN_IDENTITY",
      '"iPhone Distribution"',
      BUILD_CONFIG,
      TARGET_NAME,
    );
    proj.updateBuildProperty("DEVELOPMENT_TEAM", team, BUILD_CONFIG, TARGET_NAME);

    return cfg;
  });
};
