/**
 * `patchBusArrivalWidgetSwift` rewrites code generated by another package
 * (expo-widgets' widget template), so its guard against that template
 * changing is the part worth pinning.
 */
import { describe, it, expect } from '@jest/globals';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { patchBusArrivalWidgetSwift } = require('../withBusArrivalRefreshIntent') as {
  patchBusArrivalWidgetSwift: (source: string) => string;
};

// What expo-widgets 56 generates for BusArrivalWidget.
const GENERATED = `import WidgetKit
import SwiftUI
internal import ExpoWidgets

struct BusArrivalWidget: Widget {
  let name: String = "BusArrivalWidget"

  var body: some WidgetConfiguration {
    StaticConfiguration(kind: name, provider: WidgetsTimelineProvider(name: name)) { entry in
      WidgetsEntryView(entry: entry)
    }
    .configurationDisplayName("인입런")
    .supportedFamilies([.systemSmall])
  }
}`;

describe('patchBusArrivalWidgetSwift', () => {
  it('swaps the entry view for the one with the refresh button', () => {
    const patched = patchBusArrivalWidgetSwift(GENERATED);
    expect(patched).toContain('BusArrivalEntryView(entry: entry)');
    expect(patched).not.toContain('WidgetsEntryView(entry: entry)');
  });

  it('is idempotent', () => {
    const once = patchBusArrivalWidgetSwift(GENERATED);
    expect(patchBusArrivalWidgetSwift(once)).toBe(once);
  });

  it('throws when the generated template no longer matches', () => {
    expect(() => patchBusArrivalWidgetSwift(GENERATED.replace('WidgetsEntryView', 'EntryView'))).toThrow(
      /template has changed/,
    );
  });
});
